config/routes.rb
NuvolaApp::Application.routes.draw do
  
  

 

  get "purchases/new"

    
  get "orders/new"

  get "microposts/create"

  get "microposts/destroy"
    get "users/my_courses"
    get "courses/edit"

    
resources :users
resources :sessions, :only => [ :new, :create, :destroy ]
    resources :courses
resources :courses do
        resources :orders
    end
resources :microposts, :only => [ :create, :destroy ]
resources :orders

match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
match '/about', :to => 'pages#about'
match '/contact', :to => 'pages#contact'
match '/communities', :to => 'pages#communities'
match '/trending', :to => 'pages#trending'
match '/new', :to => 'classes#new'
match '/course_creation', :to => 'courses#new'
match '/admin', :to => 'pages#admin'
    match '/courses/:id/purchases', :to => 'purchases#new'
    match '/my_courses', :to => 'users#my_courses'
root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>**Need to get an about us**</p>

app/views/pages/admin.html.erb
<h1>Admininistrator View</h1>

<h2>
<ul>
<li><%= link_to "Course Creation", course_creation_path %></li>
<li><%= link_to "Manage Users", users_path %></li>
<li><%= link_to "Enroll Users", '#' %></li>
<li><%= link_to "Final Course List", 'finalcourses' %></li>
</ul>
</h2>

app/views/pages/classes.html.erb
<h1>Choose A Class:</h1>

		<classes>
			<u1>
				<li><%= link_to "Intro to School Safety - Module 1", '/classes/schoolsafety1' %></li>
				<li><%= link_to "Intro to School Safety - Module 2 (Coming Soon)", '/classes/schoolsafety2' %></li>
				<li><%= link_to "Intro to School Safety - Module 3 (Coming Soon)", '/classes/schoolsafety3' %></li>
				</u1>
		</classes>

app/views/pages/communities.html.erb
<h1>Communities</h1>

<p>
Join a community and learn from others
</p>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<h1>Contact Us</h1>
 <br />
<br />
<p>
	For any additional info or suggestions please contact us at <%= mail_to "info@nuvola-networks.com" %> or call us at 512-698-8913.
	
	<p>Thanks!</p>
	</p>
	

app/views/pages/home.html.erb
	<h1>Home</h1>
	<p>
	**Need to get info for Home page**</p>	
		<p>
		</p>
			<p>
		
	<a href="http://app.nuvola-academy.com/">Nuvola Academy</a> is a revolutionary approach to eLearning.  Build communities, see what's trending, and connect with like minded individuals who share a passion similar to your own.     
	</p>

<%= link_to "Sign Up Now!", signup_path, :class => "signup_button round " %>

app/views/pages/schoolsafety1.html.erb
<h1>Introduction to School Safety</h1>

<p>
Description:
</p>

<p>
Preview:</p>

<h2>
Cost: TBD - Comming Soon!
</h2>

app/views/pages/schoolsafety2.html.erb
<h1>Introduction to School Safety - Module 1</h1>

<p>
Description:
</p>

<p>
Preview:</p>

<h2>
Cost: TBD - Comming Soon!
</h2>

app/views/pages/schoolsafety3.html.erb
<h1>Introduction to School Safety - Module 2</h1>

<p>
Description: An introduction to School Safety **fill in later**
</p>

<p>
Preview:  **Add short video preview
</p>



<h2>
Cost: $TBD  <li><%= link_to "Purchase", '#' %></li>
</h2>

app/views/pages/tcpip.html.erb
<h1>Intro to Networking - TCP/IP</h1>

<p>
Description:
</p>

<p>
Preview:</p>

<h2>
Cost: TBD - Comming Soon!
</h2>

app/views/pages/trending.html.erb
<h1>Trending</h1>

<p>
See what's trending and sign up for classes
</p>

<table class="front" summary="For signed in users">
	<tr>
	
	<td class="main">
		<h1 class="micropost">What's up?</h1>
		<%= render 'shared/micropost_form' %>
		</td>
		<td class="sidebar round">
			<%= render 'shared/user_info' %>
			</td>
		</tr>
		</table>
		
		

app/views/pages/win7.html.erb
<h1>Intro to Windows 7</h1>

<p>
Description:
</p>

<p>
Preview:</p>

<h2>
Cost: TBD - Comming Soon!
</h2>