config/routes.rb
NuvolaApp::Application.routes.draw do
  
  

 

  get "purchases/new"

    
  get "orders/new"

  get "microposts/create"

  get "microposts/destroy"
    get "users/my_courses"
    get "courses/edit"

    
resources :users
resources :sessions, :only => [ :new, :create, :destroy ]
    resources :courses
resources :courses do
        resources :orders
    end
resources :microposts, :only => [ :create, :destroy ]
resources :orders

match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
match '/about', :to => 'pages#about'
match '/contact', :to => 'pages#contact'
match '/communities', :to => 'pages#communities'
match '/trending', :to => 'pages#trending'
match '/new', :to => 'classes#new'
match '/course_creation', :to => 'courses#new'
match '/admin', :to => 'pages#admin'
    match '/courses/:id/purchases', :to => 'purchases#new'
    match '/my_courses', :to => 'users#my_courses'
root :to => 'pages#home'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    
    before_filter :admin_user,   :only => [:destroy, :create, :edit, :update]

  def index
	@courses = Course.all
	@title = "Available Classes"
end
 
  def show
	@course = Course.find(params[:id])
    @order = Order.new
	@title = @course.title
end

  def new
	@course = Course.new
      @order = Order.new
      @video = Video.new
      3.times do
          video = @course.videos.build
          
      end
	@title = "New Course Creation"
  end

  def create
      @course = Course.new(params[:course])
        if  @course.save
           
        redirect_to @course
	else
	@title = "New Course Creation"
	render 'new'

end      
end
   def edit
       @course = Course.find(params[:id])
	@title = "Edit title"
	end

   def update
	@course = Course.find(params[:id])
	if @course.update_attributes(params[:course])
	flash[:success] = "Course Updated."
	redirect_to @course
else
	@title = "Edit Course"
	render 'edit'
end
end  

    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end 
  
  def destroy
	Course.find(params[:id]).destroy
	flash[:success] = "Course destroyed."
	redirect_to courses_path
end

    def admin_user
	redirect_to(root_path) unless current_user.admin?
end
end

app/helpers/courses_helper.rb
module CoursesHelper
    

end

app/views/courses/_form.html.erb
<h1>Course Creation</h1>
	
	<h2>Course Preview Content</h2>
<%= form_for @course do |f| %>
 
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label "Preview Media URL" %><br />
    <%= f.text_field :media_url %>
  </p>
<p>
	<%= f.label :cost %><br />
	$<%= f.number_field :cost %>
</p>
<h2>Course Content:</h2>
<p>
  <%= f.fields_for :videos do |builder| %>
    <%= render "video_fields", :f => builder %>
<% end %>
<p><%= link_to_add_fields "Add Another Module", f, :videos %></p>
</p>



  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/courses/_video.html.erb
<% new_or_existing = video.new_record? ? 'new' : 'existing' %> 
<% prefix = "course[#{new_or_existing}_video_attributes][]" %> 
<% fields_for prefix, video do |video_form| -%>

Video URL: <%= video_form.text_field :media_url %> 

<% end -%>

app/views/courses/_video_fields.html.erb
<div class="fields"><p>
	<%= f.label :Chapter, "Module Title"%>
	<%= f.text_field :chapter %>
	<a class="remove-fields" href="#">remove</a>
<%#<%= link_to_remove_fields "remove", f %>
	</p>
<p>
 <%= f.label :media_url, "Module Media Url" %><br />
  <%= f.text_area :media_url, :rows => 3 %><br />
</p>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<h1>Available Courses</h1>
<h2>
<ul class="courses">
<% @courses.each do |course| %>
	<li>
		<%= link_to course.title, course %>
		<% if current_user.admin? %>
                | <%= link_to "delete", course, :method => :delete, :confirm => "you sure?",
                                              :title => "Delete #{course.title}" %>
                <% end %>
				<% if current_user.admin? %>
		                | <%= link_to "Edit", :action => :edit, :id => course %>
						| <%= link_to "Enroll Users", :controller => :orders, :action => :new, :course_id => course %>
		                <% end %>
		
		</li>
		<% end %>
		</ul>

</h2>

app/views/courses/new.html.erb
<script>function add_fields(link, association, content) {
  var new_id = new Date().getTime();
  var regexp = new RegExp("new_" + association, "g")
  $(link).parent().before(content.replace(regexp, new_id));
}</script>

<%= render 'form' %>

	

app/views/courses/show.html.erb
<h1>
<%= @course.title %>
</h1>

<br />
<p></p>
<p></p>

<%#<% if @course.purchased? %>
<%#<% if current_user = @course.user_id %>
<% if @course.accessible_by_user?(current_user) %>


</p>
<% for video in @course.videos %>
<p><strong><%=h video.chapter %></strong></p>
<p><%=h video.media_url.html_safe %></p>
</p>
<% end %>
<% else %>
<p><strong>Description:</strong> <%= @course.description %></p><br />

<p><strong>Preview: </strong></p>
<%= @course.media_url.html_safe %><br />
<br />
<p><strong>Cost:</strong> $<%= @course.cost/100 %></p>



<%= link_to "Order This Course", new_course_order_path(@course) %>


<% end %>