config/routes.rb
NuvolaApp::Application.routes.draw do
  
  

 

  get "purchases/new"

    
  get "orders/new"

  get "microposts/create"

  get "microposts/destroy"
    get "users/my_courses"
    get "courses/edit"

    
resources :users
resources :sessions, :only => [ :new, :create, :destroy ]
    resources :courses
resources :courses do
        resources :orders
    end
resources :microposts, :only => [ :create, :destroy ]
resources :orders

match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
match '/about', :to => 'pages#about'
match '/contact', :to => 'pages#contact'
match '/communities', :to => 'pages#communities'
match '/trending', :to => 'pages#trending'
match '/new', :to => 'classes#new'
match '/course_creation', :to => 'courses#new'
match '/admin', :to => 'pages#admin'
    match '/courses/:id/purchases', :to => 'purchases#new'
    match '/my_courses', :to => 'users#my_courses'
root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="round">
 <p>

Powered by <a href="http://www.nuvola-networks.com/">Nuvola Networks</a> | An eLearning and design company specializing in dynamic web applications and learning environments to further education and development in both the corporate and continuing-education marketplace.
 </p>
</footer>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nuvola Academy | <%= @title %></title>
  <%= stylesheet_link_tag 'stylesheets/blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'stylesheets/blueprint/print', :media => 'print' %> 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "custom", :media => 'screen' %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
	</head>
	<body>
		<div class="container">
			<header>
				<%= image_tag("images/new_header.png", :alt => "Nuvola App") %>
</header>

<menu>
<% if signed_in? %>
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
<li><%= link_to "Users", users_path %></li>
<% if current_user.admin? %>
<li><%= link_to "Admin", admin_path %></li>
<% end %>
<% end %>
<% if signed_in? %>
<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Sign in", signin_path %></li>
<% end %>
</menu>				
<nav>
					<u1>
						<li><%= link_to "Home", root_path  %></li>
						<li><%= link_to "About Us", about_path %></li>
						<li><%= link_to "Available Courses", courses_path %></li>
						<li><%= link_to "Communities", communities_path %></li>
						<li><%= link_to "Trending", trending_path %></li>
						<li><%= link_to "My Classes", orders_path %></li>	
						<li><%= link_to "Contact Us", contact_path %></li>
						
					</u1>
				</nav>
				
				<section class="round">			
		<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
		
<subfooter>
<%= image_tag("images/pb_n_networks.png", :alt => "Sample App") %>
</subfooter>
		</div>
	</body>
</html>
		